# -*- coding: utf-8 -*-
"""ComponentExtraction.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/171UhfFyhIOWvk8vbJGLPf7cjb6QX_1Rd
"""

!pip install nilearn --quiet
import nilearn
import os
import nibabel as nib
from nilearn import image

"""## Reading the whole volume of  4D file



"""

PaData = "HPIC13_phase_3d_qflow_fb.nii.gz"
TimeFrame = image.load_img(PaData).shape[-1]
print(TimeFrame)
os.mkdir('Components')



"""It is a 4D nifti file. We load it into the memory to print its
shape.

All components are then a 3D image. We can then loop over the individual component

## Looping on all volumes in a 4D file

If we want to plot all the volumes in this 4D file, we can use iter_img
to loop on them.
"""

for img,i in zip(image.iter_img(PaData),range(1,TimeFrame+1)):
    f = 'HPIC13_%02d.nii.gz' % i
    # img is now an in-memory 3D img
    nib.save(img,os.path.join('Components',f))

